package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Arearole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AreaRole.AreaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AreaRole.roleId
     *
     * @mbg.generated
     */
    private BigDecimal roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AreaRole
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AreaRole.AreaCode
     *
     * @return the value of AreaRole.AreaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AreaRole.AreaCode
     *
     * @param areacode the value for AreaRole.AreaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AreaRole.roleId
     *
     * @return the value of AreaRole.roleId
     *
     * @mbg.generated
     */
    public BigDecimal getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AreaRole.roleId
     *
     * @param roleid the value for AreaRole.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(BigDecimal roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaRole
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areacode=").append(areacode);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}