package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Companyinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.CompanyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.AreaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.CompanyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.CompanyCode
     *
     * @mbg.generated
     */
    private String companycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.mainName
     *
     * @mbg.generated
     */
    private String mainname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.peopleName
     *
     * @mbg.generated
     */
    private String peoplename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.mobilePhone
     *
     * @mbg.generated
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.flagHealth
     *
     * @mbg.generated
     */
    private String flaghealth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.ruYuan
     *
     * @mbg.generated
     */
    private String ruyuan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.AcquisitionLicenseTime
     *
     * @mbg.generated
     */
    private Date acquisitionlicensetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.AcquisitionLicenseValid
     *
     * @mbg.generated
     */
    private String acquisitionlicensevalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.AcquisitionLicenseNo
     *
     * @mbg.generated
     */
    private String acquisitionlicenseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.CompanyType
     *
     * @mbg.generated
     */
    private String companytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.AreaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.updateDate
     *
     * @mbg.generated
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CompanyInfo.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.CompanyId
     *
     * @return the value of CompanyInfo.CompanyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.CompanyId
     *
     * @param companyid the value for CompanyInfo.CompanyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.AreaCode
     *
     * @return the value of CompanyInfo.AreaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.AreaCode
     *
     * @param areacode the value for CompanyInfo.AreaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.CompanyName
     *
     * @return the value of CompanyInfo.CompanyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.CompanyName
     *
     * @param companyname the value for CompanyInfo.CompanyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.CompanyCode
     *
     * @return the value of CompanyInfo.CompanyCode
     *
     * @mbg.generated
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.CompanyCode
     *
     * @param companycode the value for CompanyInfo.CompanyCode
     *
     * @mbg.generated
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode == null ? null : companycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.address
     *
     * @return the value of CompanyInfo.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.address
     *
     * @param address the value for CompanyInfo.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.mainName
     *
     * @return the value of CompanyInfo.mainName
     *
     * @mbg.generated
     */
    public String getMainname() {
        return mainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.mainName
     *
     * @param mainname the value for CompanyInfo.mainName
     *
     * @mbg.generated
     */
    public void setMainname(String mainname) {
        this.mainname = mainname == null ? null : mainname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.peopleName
     *
     * @return the value of CompanyInfo.peopleName
     *
     * @mbg.generated
     */
    public String getPeoplename() {
        return peoplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.peopleName
     *
     * @param peoplename the value for CompanyInfo.peopleName
     *
     * @mbg.generated
     */
    public void setPeoplename(String peoplename) {
        this.peoplename = peoplename == null ? null : peoplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.phone
     *
     * @return the value of CompanyInfo.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.phone
     *
     * @param phone the value for CompanyInfo.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.mobilePhone
     *
     * @return the value of CompanyInfo.mobilePhone
     *
     * @mbg.generated
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.mobilePhone
     *
     * @param mobilephone the value for CompanyInfo.mobilePhone
     *
     * @mbg.generated
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.email
     *
     * @return the value of CompanyInfo.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.email
     *
     * @param email the value for CompanyInfo.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.fax
     *
     * @return the value of CompanyInfo.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.fax
     *
     * @param fax the value for CompanyInfo.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.flagHealth
     *
     * @return the value of CompanyInfo.flagHealth
     *
     * @mbg.generated
     */
    public String getFlaghealth() {
        return flaghealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.flagHealth
     *
     * @param flaghealth the value for CompanyInfo.flagHealth
     *
     * @mbg.generated
     */
    public void setFlaghealth(String flaghealth) {
        this.flaghealth = flaghealth == null ? null : flaghealth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.ruYuan
     *
     * @return the value of CompanyInfo.ruYuan
     *
     * @mbg.generated
     */
    public String getRuyuan() {
        return ruyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.ruYuan
     *
     * @param ruyuan the value for CompanyInfo.ruYuan
     *
     * @mbg.generated
     */
    public void setRuyuan(String ruyuan) {
        this.ruyuan = ruyuan == null ? null : ruyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.AcquisitionLicenseTime
     *
     * @return the value of CompanyInfo.AcquisitionLicenseTime
     *
     * @mbg.generated
     */
    public Date getAcquisitionlicensetime() {
        return acquisitionlicensetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.AcquisitionLicenseTime
     *
     * @param acquisitionlicensetime the value for CompanyInfo.AcquisitionLicenseTime
     *
     * @mbg.generated
     */
    public void setAcquisitionlicensetime(Date acquisitionlicensetime) {
        this.acquisitionlicensetime = acquisitionlicensetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.AcquisitionLicenseValid
     *
     * @return the value of CompanyInfo.AcquisitionLicenseValid
     *
     * @mbg.generated
     */
    public String getAcquisitionlicensevalid() {
        return acquisitionlicensevalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.AcquisitionLicenseValid
     *
     * @param acquisitionlicensevalid the value for CompanyInfo.AcquisitionLicenseValid
     *
     * @mbg.generated
     */
    public void setAcquisitionlicensevalid(String acquisitionlicensevalid) {
        this.acquisitionlicensevalid = acquisitionlicensevalid == null ? null : acquisitionlicensevalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.AcquisitionLicenseNo
     *
     * @return the value of CompanyInfo.AcquisitionLicenseNo
     *
     * @mbg.generated
     */
    public String getAcquisitionlicenseno() {
        return acquisitionlicenseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.AcquisitionLicenseNo
     *
     * @param acquisitionlicenseno the value for CompanyInfo.AcquisitionLicenseNo
     *
     * @mbg.generated
     */
    public void setAcquisitionlicenseno(String acquisitionlicenseno) {
        this.acquisitionlicenseno = acquisitionlicenseno == null ? null : acquisitionlicenseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.CompanyType
     *
     * @return the value of CompanyInfo.CompanyType
     *
     * @mbg.generated
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.CompanyType
     *
     * @param companytype the value for CompanyInfo.CompanyType
     *
     * @mbg.generated
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype == null ? null : companytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.AreaName
     *
     * @return the value of CompanyInfo.AreaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.AreaName
     *
     * @param areaname the value for CompanyInfo.AreaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.createDate
     *
     * @return the value of CompanyInfo.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.createDate
     *
     * @param createdate the value for CompanyInfo.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.updateDate
     *
     * @return the value of CompanyInfo.updateDate
     *
     * @mbg.generated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.updateDate
     *
     * @param updatedate the value for CompanyInfo.updateDate
     *
     * @mbg.generated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.attrbute1
     *
     * @return the value of CompanyInfo.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.attrbute1
     *
     * @param attrbute1 the value for CompanyInfo.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.attrbute2
     *
     * @return the value of CompanyInfo.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.attrbute2
     *
     * @param attrbute2 the value for CompanyInfo.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.attrbute3
     *
     * @return the value of CompanyInfo.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.attrbute3
     *
     * @param attrbute3 the value for CompanyInfo.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.attrbute4
     *
     * @return the value of CompanyInfo.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.attrbute4
     *
     * @param attrbute4 the value for CompanyInfo.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CompanyInfo.attrbute5
     *
     * @return the value of CompanyInfo.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CompanyInfo.attrbute5
     *
     * @param attrbute5 the value for CompanyInfo.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", companyid=").append(companyid);
        sb.append(", areacode=").append(areacode);
        sb.append(", companyname=").append(companyname);
        sb.append(", companycode=").append(companycode);
        sb.append(", address=").append(address);
        sb.append(", mainname=").append(mainname);
        sb.append(", peoplename=").append(peoplename);
        sb.append(", phone=").append(phone);
        sb.append(", mobilephone=").append(mobilephone);
        sb.append(", email=").append(email);
        sb.append(", fax=").append(fax);
        sb.append(", flaghealth=").append(flaghealth);
        sb.append(", ruyuan=").append(ruyuan);
        sb.append(", acquisitionlicensetime=").append(acquisitionlicensetime);
        sb.append(", acquisitionlicensevalid=").append(acquisitionlicensevalid);
        sb.append(", acquisitionlicenseno=").append(acquisitionlicenseno);
        sb.append(", companytype=").append(companytype);
        sb.append(", areaname=").append(areaname);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}