package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Handmilksilos implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.hmsId
     *
     * @mbg.generated
     */
    private BigDecimal hmsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.HandoverId
     *
     * @mbg.generated
     */
    private BigDecimal handoverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.MilkSilosNo
     *
     * @mbg.generated
     */
    private String milksilosno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.fat
     *
     * @mbg.generated
     */
    private String fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.protein
     *
     * @mbg.generated
     */
    private String protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.Microorganism
     *
     * @mbg.generated
     */
    private String microorganism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.soma
     *
     * @mbg.generated
     */
    private String soma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.userId
     *
     * @mbg.generated
     */
    private BigDecimal userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.hatchTitle
     *
     * @mbg.generated
     */
    private String hatchtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.valveTitle
     *
     * @mbg.generated
     */
    private String valvetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HandMilkSilos.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.hmsId
     *
     * @return the value of HandMilkSilos.hmsId
     *
     * @mbg.generated
     */
    public BigDecimal getHmsid() {
        return hmsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.hmsId
     *
     * @param hmsid the value for HandMilkSilos.hmsId
     *
     * @mbg.generated
     */
    public void setHmsid(BigDecimal hmsid) {
        this.hmsid = hmsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.HandoverId
     *
     * @return the value of HandMilkSilos.HandoverId
     *
     * @mbg.generated
     */
    public BigDecimal getHandoverid() {
        return handoverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.HandoverId
     *
     * @param handoverid the value for HandMilkSilos.HandoverId
     *
     * @mbg.generated
     */
    public void setHandoverid(BigDecimal handoverid) {
        this.handoverid = handoverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.MilkSilosNo
     *
     * @return the value of HandMilkSilos.MilkSilosNo
     *
     * @mbg.generated
     */
    public String getMilksilosno() {
        return milksilosno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.MilkSilosNo
     *
     * @param milksilosno the value for HandMilkSilos.MilkSilosNo
     *
     * @mbg.generated
     */
    public void setMilksilosno(String milksilosno) {
        this.milksilosno = milksilosno == null ? null : milksilosno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.fat
     *
     * @return the value of HandMilkSilos.fat
     *
     * @mbg.generated
     */
    public String getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.fat
     *
     * @param fat the value for HandMilkSilos.fat
     *
     * @mbg.generated
     */
    public void setFat(String fat) {
        this.fat = fat == null ? null : fat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.protein
     *
     * @return the value of HandMilkSilos.protein
     *
     * @mbg.generated
     */
    public String getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.protein
     *
     * @param protein the value for HandMilkSilos.protein
     *
     * @mbg.generated
     */
    public void setProtein(String protein) {
        this.protein = protein == null ? null : protein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.Microorganism
     *
     * @return the value of HandMilkSilos.Microorganism
     *
     * @mbg.generated
     */
    public String getMicroorganism() {
        return microorganism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.Microorganism
     *
     * @param microorganism the value for HandMilkSilos.Microorganism
     *
     * @mbg.generated
     */
    public void setMicroorganism(String microorganism) {
        this.microorganism = microorganism == null ? null : microorganism.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.soma
     *
     * @return the value of HandMilkSilos.soma
     *
     * @mbg.generated
     */
    public String getSoma() {
        return soma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.soma
     *
     * @param soma the value for HandMilkSilos.soma
     *
     * @mbg.generated
     */
    public void setSoma(String soma) {
        this.soma = soma == null ? null : soma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.userId
     *
     * @return the value of HandMilkSilos.userId
     *
     * @mbg.generated
     */
    public BigDecimal getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.userId
     *
     * @param userid the value for HandMilkSilos.userId
     *
     * @mbg.generated
     */
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.userName
     *
     * @return the value of HandMilkSilos.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.userName
     *
     * @param username the value for HandMilkSilos.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.status
     *
     * @return the value of HandMilkSilos.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.status
     *
     * @param status the value for HandMilkSilos.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.hatchTitle
     *
     * @return the value of HandMilkSilos.hatchTitle
     *
     * @mbg.generated
     */
    public String getHatchtitle() {
        return hatchtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.hatchTitle
     *
     * @param hatchtitle the value for HandMilkSilos.hatchTitle
     *
     * @mbg.generated
     */
    public void setHatchtitle(String hatchtitle) {
        this.hatchtitle = hatchtitle == null ? null : hatchtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.valveTitle
     *
     * @return the value of HandMilkSilos.valveTitle
     *
     * @mbg.generated
     */
    public String getValvetitle() {
        return valvetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.valveTitle
     *
     * @param valvetitle the value for HandMilkSilos.valveTitle
     *
     * @mbg.generated
     */
    public void setValvetitle(String valvetitle) {
        this.valvetitle = valvetitle == null ? null : valvetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.photo
     *
     * @return the value of HandMilkSilos.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.photo
     *
     * @param photo the value for HandMilkSilos.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.attrbute1
     *
     * @return the value of HandMilkSilos.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.attrbute1
     *
     * @param attrbute1 the value for HandMilkSilos.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.attrbute2
     *
     * @return the value of HandMilkSilos.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.attrbute2
     *
     * @param attrbute2 the value for HandMilkSilos.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.attrbute3
     *
     * @return the value of HandMilkSilos.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.attrbute3
     *
     * @param attrbute3 the value for HandMilkSilos.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.attrbute4
     *
     * @return the value of HandMilkSilos.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.attrbute4
     *
     * @param attrbute4 the value for HandMilkSilos.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HandMilkSilos.attrbute5
     *
     * @return the value of HandMilkSilos.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HandMilkSilos.attrbute5
     *
     * @param attrbute5 the value for HandMilkSilos.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hmsid=").append(hmsid);
        sb.append(", handoverid=").append(handoverid);
        sb.append(", milksilosno=").append(milksilosno);
        sb.append(", fat=").append(fat);
        sb.append(", protein=").append(protein);
        sb.append(", microorganism=").append(microorganism);
        sb.append(", soma=").append(soma);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", status=").append(status);
        sb.append(", hatchtitle=").append(hatchtitle);
        sb.append(", valvetitle=").append(valvetitle);
        sb.append(", photo=").append(photo);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}