package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Handover implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.HandoverId
     *
     * @mbg.generated
     */
    private BigDecimal handoverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.HandoverNo
     *
     * @mbg.generated
     */
    private String handoverno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.CompanyMilkId
     *
     * @mbg.generated
     */
    private BigDecimal companymilkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.CompanyMilkName
     *
     * @mbg.generated
     */
    private String companymilkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.TruckPateNo
     *
     * @mbg.generated
     */
    private String truckpateno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.TruckNo
     *
     * @mbg.generated
     */
    private String truckno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.TruckId
     *
     * @mbg.generated
     */
    private BigDecimal truckid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.CompanyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.CompanyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.ArrivalDate
     *
     * @mbg.generated
     */
    private String arrivaldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.DepartureDate
     *
     * @mbg.generated
     */
    private String departuredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.milkTest
     *
     * @mbg.generated
     */
    private String milktest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.detectionResult
     *
     * @mbg.generated
     */
    private String detectionresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.health
     *
     * @mbg.generated
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.LoadingCapacity
     *
     * @mbg.generated
     */
    private String loadingcapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.temperature
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.abnormal
     *
     * @mbg.generated
     */
    private String abnormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.operation
     *
     * @mbg.generated
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.carName
     *
     * @mbg.generated
     */
    private String carname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.carPhone
     *
     * @mbg.generated
     */
    private String carphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.struts
     *
     * @mbg.generated
     */
    private String struts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.milkHarvest
     *
     * @mbg.generated
     */
    private String milkharvest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.rejection
     *
     * @mbg.generated
     */
    private String rejection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.rejectionDesc
     *
     * @mbg.generated
     */
    private String rejectiondesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.Contraband
     *
     * @mbg.generated
     */
    private String contraband;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Handover.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Handover
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.HandoverId
     *
     * @return the value of Handover.HandoverId
     *
     * @mbg.generated
     */
    public BigDecimal getHandoverid() {
        return handoverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.HandoverId
     *
     * @param handoverid the value for Handover.HandoverId
     *
     * @mbg.generated
     */
    public void setHandoverid(BigDecimal handoverid) {
        this.handoverid = handoverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.HandoverNo
     *
     * @return the value of Handover.HandoverNo
     *
     * @mbg.generated
     */
    public String getHandoverno() {
        return handoverno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.HandoverNo
     *
     * @param handoverno the value for Handover.HandoverNo
     *
     * @mbg.generated
     */
    public void setHandoverno(String handoverno) {
        this.handoverno = handoverno == null ? null : handoverno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.CompanyMilkId
     *
     * @return the value of Handover.CompanyMilkId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanymilkid() {
        return companymilkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.CompanyMilkId
     *
     * @param companymilkid the value for Handover.CompanyMilkId
     *
     * @mbg.generated
     */
    public void setCompanymilkid(BigDecimal companymilkid) {
        this.companymilkid = companymilkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.CompanyMilkName
     *
     * @return the value of Handover.CompanyMilkName
     *
     * @mbg.generated
     */
    public String getCompanymilkname() {
        return companymilkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.CompanyMilkName
     *
     * @param companymilkname the value for Handover.CompanyMilkName
     *
     * @mbg.generated
     */
    public void setCompanymilkname(String companymilkname) {
        this.companymilkname = companymilkname == null ? null : companymilkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.TruckPateNo
     *
     * @return the value of Handover.TruckPateNo
     *
     * @mbg.generated
     */
    public String getTruckpateno() {
        return truckpateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.TruckPateNo
     *
     * @param truckpateno the value for Handover.TruckPateNo
     *
     * @mbg.generated
     */
    public void setTruckpateno(String truckpateno) {
        this.truckpateno = truckpateno == null ? null : truckpateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.TruckNo
     *
     * @return the value of Handover.TruckNo
     *
     * @mbg.generated
     */
    public String getTruckno() {
        return truckno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.TruckNo
     *
     * @param truckno the value for Handover.TruckNo
     *
     * @mbg.generated
     */
    public void setTruckno(String truckno) {
        this.truckno = truckno == null ? null : truckno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.TruckId
     *
     * @return the value of Handover.TruckId
     *
     * @mbg.generated
     */
    public BigDecimal getTruckid() {
        return truckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.TruckId
     *
     * @param truckid the value for Handover.TruckId
     *
     * @mbg.generated
     */
    public void setTruckid(BigDecimal truckid) {
        this.truckid = truckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.createDate
     *
     * @return the value of Handover.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.createDate
     *
     * @param createdate the value for Handover.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.CompanyId
     *
     * @return the value of Handover.CompanyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.CompanyId
     *
     * @param companyid the value for Handover.CompanyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.CompanyName
     *
     * @return the value of Handover.CompanyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.CompanyName
     *
     * @param companyname the value for Handover.CompanyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.ArrivalDate
     *
     * @return the value of Handover.ArrivalDate
     *
     * @mbg.generated
     */
    public String getArrivaldate() {
        return arrivaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.ArrivalDate
     *
     * @param arrivaldate the value for Handover.ArrivalDate
     *
     * @mbg.generated
     */
    public void setArrivaldate(String arrivaldate) {
        this.arrivaldate = arrivaldate == null ? null : arrivaldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.DepartureDate
     *
     * @return the value of Handover.DepartureDate
     *
     * @mbg.generated
     */
    public String getDeparturedate() {
        return departuredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.DepartureDate
     *
     * @param departuredate the value for Handover.DepartureDate
     *
     * @mbg.generated
     */
    public void setDeparturedate(String departuredate) {
        this.departuredate = departuredate == null ? null : departuredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.milkTest
     *
     * @return the value of Handover.milkTest
     *
     * @mbg.generated
     */
    public String getMilktest() {
        return milktest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.milkTest
     *
     * @param milktest the value for Handover.milkTest
     *
     * @mbg.generated
     */
    public void setMilktest(String milktest) {
        this.milktest = milktest == null ? null : milktest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.detectionResult
     *
     * @return the value of Handover.detectionResult
     *
     * @mbg.generated
     */
    public String getDetectionresult() {
        return detectionresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.detectionResult
     *
     * @param detectionresult the value for Handover.detectionResult
     *
     * @mbg.generated
     */
    public void setDetectionresult(String detectionresult) {
        this.detectionresult = detectionresult == null ? null : detectionresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.health
     *
     * @return the value of Handover.health
     *
     * @mbg.generated
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.health
     *
     * @param health the value for Handover.health
     *
     * @mbg.generated
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.LoadingCapacity
     *
     * @return the value of Handover.LoadingCapacity
     *
     * @mbg.generated
     */
    public String getLoadingcapacity() {
        return loadingcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.LoadingCapacity
     *
     * @param loadingcapacity the value for Handover.LoadingCapacity
     *
     * @mbg.generated
     */
    public void setLoadingcapacity(String loadingcapacity) {
        this.loadingcapacity = loadingcapacity == null ? null : loadingcapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.temperature
     *
     * @return the value of Handover.temperature
     *
     * @mbg.generated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.temperature
     *
     * @param temperature the value for Handover.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.abnormal
     *
     * @return the value of Handover.abnormal
     *
     * @mbg.generated
     */
    public String getAbnormal() {
        return abnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.abnormal
     *
     * @param abnormal the value for Handover.abnormal
     *
     * @mbg.generated
     */
    public void setAbnormal(String abnormal) {
        this.abnormal = abnormal == null ? null : abnormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.operation
     *
     * @return the value of Handover.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.operation
     *
     * @param operation the value for Handover.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.carName
     *
     * @return the value of Handover.carName
     *
     * @mbg.generated
     */
    public String getCarname() {
        return carname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.carName
     *
     * @param carname the value for Handover.carName
     *
     * @mbg.generated
     */
    public void setCarname(String carname) {
        this.carname = carname == null ? null : carname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.carPhone
     *
     * @return the value of Handover.carPhone
     *
     * @mbg.generated
     */
    public String getCarphone() {
        return carphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.carPhone
     *
     * @param carphone the value for Handover.carPhone
     *
     * @mbg.generated
     */
    public void setCarphone(String carphone) {
        this.carphone = carphone == null ? null : carphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.struts
     *
     * @return the value of Handover.struts
     *
     * @mbg.generated
     */
    public String getStruts() {
        return struts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.struts
     *
     * @param struts the value for Handover.struts
     *
     * @mbg.generated
     */
    public void setStruts(String struts) {
        this.struts = struts == null ? null : struts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.milkHarvest
     *
     * @return the value of Handover.milkHarvest
     *
     * @mbg.generated
     */
    public String getMilkharvest() {
        return milkharvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.milkHarvest
     *
     * @param milkharvest the value for Handover.milkHarvest
     *
     * @mbg.generated
     */
    public void setMilkharvest(String milkharvest) {
        this.milkharvest = milkharvest == null ? null : milkharvest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.rejection
     *
     * @return the value of Handover.rejection
     *
     * @mbg.generated
     */
    public String getRejection() {
        return rejection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.rejection
     *
     * @param rejection the value for Handover.rejection
     *
     * @mbg.generated
     */
    public void setRejection(String rejection) {
        this.rejection = rejection == null ? null : rejection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.rejectionDesc
     *
     * @return the value of Handover.rejectionDesc
     *
     * @mbg.generated
     */
    public String getRejectiondesc() {
        return rejectiondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.rejectionDesc
     *
     * @param rejectiondesc the value for Handover.rejectionDesc
     *
     * @mbg.generated
     */
    public void setRejectiondesc(String rejectiondesc) {
        this.rejectiondesc = rejectiondesc == null ? null : rejectiondesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.Contraband
     *
     * @return the value of Handover.Contraband
     *
     * @mbg.generated
     */
    public String getContraband() {
        return contraband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.Contraband
     *
     * @param contraband the value for Handover.Contraband
     *
     * @mbg.generated
     */
    public void setContraband(String contraband) {
        this.contraband = contraband == null ? null : contraband.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.attrbute1
     *
     * @return the value of Handover.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.attrbute1
     *
     * @param attrbute1 the value for Handover.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.attrbute2
     *
     * @return the value of Handover.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.attrbute2
     *
     * @param attrbute2 the value for Handover.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.attrbute3
     *
     * @return the value of Handover.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.attrbute3
     *
     * @param attrbute3 the value for Handover.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.attrbute4
     *
     * @return the value of Handover.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.attrbute4
     *
     * @param attrbute4 the value for Handover.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Handover.attrbute5
     *
     * @return the value of Handover.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Handover.attrbute5
     *
     * @param attrbute5 the value for Handover.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Handover
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", handoverid=").append(handoverid);
        sb.append(", handoverno=").append(handoverno);
        sb.append(", companymilkid=").append(companymilkid);
        sb.append(", companymilkname=").append(companymilkname);
        sb.append(", truckpateno=").append(truckpateno);
        sb.append(", truckno=").append(truckno);
        sb.append(", truckid=").append(truckid);
        sb.append(", createdate=").append(createdate);
        sb.append(", companyid=").append(companyid);
        sb.append(", companyname=").append(companyname);
        sb.append(", arrivaldate=").append(arrivaldate);
        sb.append(", departuredate=").append(departuredate);
        sb.append(", milktest=").append(milktest);
        sb.append(", detectionresult=").append(detectionresult);
        sb.append(", health=").append(health);
        sb.append(", loadingcapacity=").append(loadingcapacity);
        sb.append(", temperature=").append(temperature);
        sb.append(", abnormal=").append(abnormal);
        sb.append(", operation=").append(operation);
        sb.append(", carname=").append(carname);
        sb.append(", carphone=").append(carphone);
        sb.append(", struts=").append(struts);
        sb.append(", milkharvest=").append(milkharvest);
        sb.append(", rejection=").append(rejection);
        sb.append(", rejectiondesc=").append(rejectiondesc);
        sb.append(", contraband=").append(contraband);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}