package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Milkcontainerinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.mcId
     *
     * @mbg.generated
     */
    private BigDecimal mcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.CompanyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.mcNo
     *
     * @mbg.generated
     */
    private String mcno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.mcName
     *
     * @mbg.generated
     */
    private String mcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.mcPosition
     *
     * @mbg.generated
     */
    private String mcposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.temperature
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.updateDate
     *
     * @mbg.generated
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MilkContainerInfo.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.mcId
     *
     * @return the value of MilkContainerInfo.mcId
     *
     * @mbg.generated
     */
    public BigDecimal getMcid() {
        return mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.mcId
     *
     * @param mcid the value for MilkContainerInfo.mcId
     *
     * @mbg.generated
     */
    public void setMcid(BigDecimal mcid) {
        this.mcid = mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.CompanyId
     *
     * @return the value of MilkContainerInfo.CompanyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.CompanyId
     *
     * @param companyid the value for MilkContainerInfo.CompanyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.mcNo
     *
     * @return the value of MilkContainerInfo.mcNo
     *
     * @mbg.generated
     */
    public String getMcno() {
        return mcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.mcNo
     *
     * @param mcno the value for MilkContainerInfo.mcNo
     *
     * @mbg.generated
     */
    public void setMcno(String mcno) {
        this.mcno = mcno == null ? null : mcno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.mcName
     *
     * @return the value of MilkContainerInfo.mcName
     *
     * @mbg.generated
     */
    public String getMcname() {
        return mcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.mcName
     *
     * @param mcname the value for MilkContainerInfo.mcName
     *
     * @mbg.generated
     */
    public void setMcname(String mcname) {
        this.mcname = mcname == null ? null : mcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.mcPosition
     *
     * @return the value of MilkContainerInfo.mcPosition
     *
     * @mbg.generated
     */
    public String getMcposition() {
        return mcposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.mcPosition
     *
     * @param mcposition the value for MilkContainerInfo.mcPosition
     *
     * @mbg.generated
     */
    public void setMcposition(String mcposition) {
        this.mcposition = mcposition == null ? null : mcposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.temperature
     *
     * @return the value of MilkContainerInfo.temperature
     *
     * @mbg.generated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.temperature
     *
     * @param temperature the value for MilkContainerInfo.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.weight
     *
     * @return the value of MilkContainerInfo.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.weight
     *
     * @param weight the value for MilkContainerInfo.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.updateDate
     *
     * @return the value of MilkContainerInfo.updateDate
     *
     * @mbg.generated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.updateDate
     *
     * @param updatedate the value for MilkContainerInfo.updateDate
     *
     * @mbg.generated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.createDate
     *
     * @return the value of MilkContainerInfo.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.createDate
     *
     * @param createdate the value for MilkContainerInfo.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.attrbute1
     *
     * @return the value of MilkContainerInfo.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.attrbute1
     *
     * @param attrbute1 the value for MilkContainerInfo.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.attrbute2
     *
     * @return the value of MilkContainerInfo.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.attrbute2
     *
     * @param attrbute2 the value for MilkContainerInfo.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.attrbute3
     *
     * @return the value of MilkContainerInfo.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.attrbute3
     *
     * @param attrbute3 the value for MilkContainerInfo.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.attrbute4
     *
     * @return the value of MilkContainerInfo.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.attrbute4
     *
     * @param attrbute4 the value for MilkContainerInfo.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MilkContainerInfo.attrbute5
     *
     * @return the value of MilkContainerInfo.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MilkContainerInfo.attrbute5
     *
     * @param attrbute5 the value for MilkContainerInfo.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mcid=").append(mcid);
        sb.append(", companyid=").append(companyid);
        sb.append(", mcno=").append(mcno);
        sb.append(", mcname=").append(mcname);
        sb.append(", mcposition=").append(mcposition);
        sb.append(", temperature=").append(temperature);
        sb.append(", weight=").append(weight);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", createdate=").append(createdate);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}