package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Milkrealtime implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.mcId
     *
     * @mbg.generated
     */
    private BigDecimal mcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.CompanyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.mcNo
     *
     * @mbg.generated
     */
    private String mcno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.temperature
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.updateDate
     *
     * @mbg.generated
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milkRealTime.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table milkRealTime
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.mcId
     *
     * @return the value of milkRealTime.mcId
     *
     * @mbg.generated
     */
    public BigDecimal getMcid() {
        return mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.mcId
     *
     * @param mcid the value for milkRealTime.mcId
     *
     * @mbg.generated
     */
    public void setMcid(BigDecimal mcid) {
        this.mcid = mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.CompanyId
     *
     * @return the value of milkRealTime.CompanyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.CompanyId
     *
     * @param companyid the value for milkRealTime.CompanyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.mcNo
     *
     * @return the value of milkRealTime.mcNo
     *
     * @mbg.generated
     */
    public String getMcno() {
        return mcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.mcNo
     *
     * @param mcno the value for milkRealTime.mcNo
     *
     * @mbg.generated
     */
    public void setMcno(String mcno) {
        this.mcno = mcno == null ? null : mcno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.temperature
     *
     * @return the value of milkRealTime.temperature
     *
     * @mbg.generated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.temperature
     *
     * @param temperature the value for milkRealTime.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.weight
     *
     * @return the value of milkRealTime.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.weight
     *
     * @param weight the value for milkRealTime.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.updateDate
     *
     * @return the value of milkRealTime.updateDate
     *
     * @mbg.generated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.updateDate
     *
     * @param updatedate the value for milkRealTime.updateDate
     *
     * @mbg.generated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.attrbute1
     *
     * @return the value of milkRealTime.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.attrbute1
     *
     * @param attrbute1 the value for milkRealTime.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.attrbute2
     *
     * @return the value of milkRealTime.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.attrbute2
     *
     * @param attrbute2 the value for milkRealTime.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.attrbute3
     *
     * @return the value of milkRealTime.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.attrbute3
     *
     * @param attrbute3 the value for milkRealTime.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.attrbute4
     *
     * @return the value of milkRealTime.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.attrbute4
     *
     * @param attrbute4 the value for milkRealTime.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milkRealTime.attrbute5
     *
     * @return the value of milkRealTime.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milkRealTime.attrbute5
     *
     * @param attrbute5 the value for milkRealTime.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table milkRealTime
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mcid=").append(mcid);
        sb.append(", companyid=").append(companyid);
        sb.append(", mcno=").append(mcno);
        sb.append(", temperature=").append(temperature);
        sb.append(", weight=").append(weight);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}