package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class SysModule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelId
     *
     * @mbg.generated
     */
    private BigDecimal modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelName
     *
     * @mbg.generated
     */
    private String modelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelParent
     *
     * @mbg.generated
     */
    private BigDecimal modelparent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelUrl
     *
     * @mbg.generated
     */
    private String modelurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelNo
     *
     * @mbg.generated
     */
    private BigDecimal modelno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.modelType
     *
     * @mbg.generated
     */
    private String modeltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_module
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelId
     *
     * @return the value of sys_module.modelId
     *
     * @mbg.generated
     */
    public BigDecimal getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelId
     *
     * @param modelid the value for sys_module.modelId
     *
     * @mbg.generated
     */
    public void setModelid(BigDecimal modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelName
     *
     * @return the value of sys_module.modelName
     *
     * @mbg.generated
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelName
     *
     * @param modelname the value for sys_module.modelName
     *
     * @mbg.generated
     */
    public void setModelname(String modelname) {
        this.modelname = modelname == null ? null : modelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelParent
     *
     * @return the value of sys_module.modelParent
     *
     * @mbg.generated
     */
    public BigDecimal getModelparent() {
        return modelparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelParent
     *
     * @param modelparent the value for sys_module.modelParent
     *
     * @mbg.generated
     */
    public void setModelparent(BigDecimal modelparent) {
        this.modelparent = modelparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelUrl
     *
     * @return the value of sys_module.modelUrl
     *
     * @mbg.generated
     */
    public String getModelurl() {
        return modelurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelUrl
     *
     * @param modelurl the value for sys_module.modelUrl
     *
     * @mbg.generated
     */
    public void setModelurl(String modelurl) {
        this.modelurl = modelurl == null ? null : modelurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelNo
     *
     * @return the value of sys_module.modelNo
     *
     * @mbg.generated
     */
    public BigDecimal getModelno() {
        return modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelNo
     *
     * @param modelno the value for sys_module.modelNo
     *
     * @mbg.generated
     */
    public void setModelno(BigDecimal modelno) {
        this.modelno = modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.modelType
     *
     * @return the value of sys_module.modelType
     *
     * @mbg.generated
     */
    public String getModeltype() {
        return modeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.modelType
     *
     * @param modeltype the value for sys_module.modelType
     *
     * @mbg.generated
     */
    public void setModeltype(String modeltype) {
        this.modeltype = modeltype == null ? null : modeltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", modelid=").append(modelid);
        sb.append(", modelname=").append(modelname);
        sb.append(", modelparent=").append(modelparent);
        sb.append(", modelurl=").append(modelurl);
        sb.append(", modelno=").append(modelno);
        sb.append(", modeltype=").append(modeltype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}