package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.id
     *
     * @mbg.generated
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.userCode
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.roleId
     *
     * @mbg.generated
     */
    private BigDecimal roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.roleName
     *
     * @mbg.generated
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.companyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.companyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.identifyNo
     *
     * @mbg.generated
     */
    private String identifyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_User.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_User
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.id
     *
     * @return the value of sys_User.id
     *
     * @mbg.generated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.id
     *
     * @param id the value for sys_User.id
     *
     * @mbg.generated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.userCode
     *
     * @return the value of sys_User.userCode
     *
     * @mbg.generated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.userCode
     *
     * @param usercode the value for sys_User.userCode
     *
     * @mbg.generated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.password
     *
     * @return the value of sys_User.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.password
     *
     * @param password the value for sys_User.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.userName
     *
     * @return the value of sys_User.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.userName
     *
     * @param username the value for sys_User.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.telephone
     *
     * @return the value of sys_User.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.telephone
     *
     * @param telephone the value for sys_User.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.email
     *
     * @return the value of sys_User.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.email
     *
     * @param email the value for sys_User.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.flag
     *
     * @return the value of sys_User.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.flag
     *
     * @param flag the value for sys_User.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.roleId
     *
     * @return the value of sys_User.roleId
     *
     * @mbg.generated
     */
    public BigDecimal getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.roleId
     *
     * @param roleid the value for sys_User.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(BigDecimal roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.roleName
     *
     * @return the value of sys_User.roleName
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.roleName
     *
     * @param rolename the value for sys_User.roleName
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.companyName
     *
     * @return the value of sys_User.companyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.companyName
     *
     * @param companyname the value for sys_User.companyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.companyId
     *
     * @return the value of sys_User.companyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.companyId
     *
     * @param companyid the value for sys_User.companyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.identifyNo
     *
     * @return the value of sys_User.identifyNo
     *
     * @mbg.generated
     */
    public String getIdentifyno() {
        return identifyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.identifyNo
     *
     * @param identifyno the value for sys_User.identifyNo
     *
     * @mbg.generated
     */
    public void setIdentifyno(String identifyno) {
        this.identifyno = identifyno == null ? null : identifyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.attrbute1
     *
     * @return the value of sys_User.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.attrbute1
     *
     * @param attrbute1 the value for sys_User.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.attrbute2
     *
     * @return the value of sys_User.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.attrbute2
     *
     * @param attrbute2 the value for sys_User.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.attrbute3
     *
     * @return the value of sys_User.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.attrbute3
     *
     * @param attrbute3 the value for sys_User.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.attrbute4
     *
     * @return the value of sys_User.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.attrbute4
     *
     * @param attrbute4 the value for sys_User.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.attrbute5
     *
     * @return the value of sys_User.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.attrbute5
     *
     * @param attrbute5 the value for sys_User.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_User.createDate
     *
     * @return the value of sys_User.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_User.createDate
     *
     * @param createdate the value for sys_User.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_User
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", usercode=").append(usercode);
        sb.append(", password=").append(password);
        sb.append(", username=").append(username);
        sb.append(", telephone=").append(telephone);
        sb.append(", email=").append(email);
        sb.append(", flag=").append(flag);
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", companyname=").append(companyname);
        sb.append(", companyid=").append(companyid);
        sb.append(", identifyno=").append(identifyno);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}