package com.spring.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Truck implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.TruckId
     *
     * @mbg.generated
     */
    private BigDecimal truckid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.licensePlate
     *
     * @mbg.generated
     */
    private String licenseplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.companyId
     *
     * @mbg.generated
     */
    private BigDecimal companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.companyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.from
     *
     * @mbg.generated
     */
    private String from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.QTPCreate
     *
     * @mbg.generated
     */
    private Date qtpcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.QTPTime
     *
     * @mbg.generated
     */
    private String qtptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.QTNO
     *
     * @mbg.generated
     */
    private String qtno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.GPSNO
     *
     * @mbg.generated
     */
    private String gpsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.MonitorCreate
     *
     * @mbg.generated
     */
    private Date monitorcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.attrbute1
     *
     * @mbg.generated
     */
    private String attrbute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.attrbute2
     *
     * @mbg.generated
     */
    private String attrbute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.attrbute3
     *
     * @mbg.generated
     */
    private String attrbute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.attrbute4
     *
     * @mbg.generated
     */
    private String attrbute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Truck.attrbute5
     *
     * @mbg.generated
     */
    private String attrbute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Truck
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.TruckId
     *
     * @return the value of Truck.TruckId
     *
     * @mbg.generated
     */
    public BigDecimal getTruckid() {
        return truckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.TruckId
     *
     * @param truckid the value for Truck.TruckId
     *
     * @mbg.generated
     */
    public void setTruckid(BigDecimal truckid) {
        this.truckid = truckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.licensePlate
     *
     * @return the value of Truck.licensePlate
     *
     * @mbg.generated
     */
    public String getLicenseplate() {
        return licenseplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.licensePlate
     *
     * @param licenseplate the value for Truck.licensePlate
     *
     * @mbg.generated
     */
    public void setLicenseplate(String licenseplate) {
        this.licenseplate = licenseplate == null ? null : licenseplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.companyId
     *
     * @return the value of Truck.companyId
     *
     * @mbg.generated
     */
    public BigDecimal getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.companyId
     *
     * @param companyid the value for Truck.companyId
     *
     * @mbg.generated
     */
    public void setCompanyid(BigDecimal companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.companyName
     *
     * @return the value of Truck.companyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.companyName
     *
     * @param companyname the value for Truck.companyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.telephone
     *
     * @return the value of Truck.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.telephone
     *
     * @param telephone the value for Truck.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.address
     *
     * @return the value of Truck.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.address
     *
     * @param address the value for Truck.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.name
     *
     * @return the value of Truck.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.name
     *
     * @param name the value for Truck.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.weight
     *
     * @return the value of Truck.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.weight
     *
     * @param weight the value for Truck.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.from
     *
     * @return the value of Truck.from
     *
     * @mbg.generated
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.from
     *
     * @param from the value for Truck.from
     *
     * @mbg.generated
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.QTPCreate
     *
     * @return the value of Truck.QTPCreate
     *
     * @mbg.generated
     */
    public Date getQtpcreate() {
        return qtpcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.QTPCreate
     *
     * @param qtpcreate the value for Truck.QTPCreate
     *
     * @mbg.generated
     */
    public void setQtpcreate(Date qtpcreate) {
        this.qtpcreate = qtpcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.QTPTime
     *
     * @return the value of Truck.QTPTime
     *
     * @mbg.generated
     */
    public String getQtptime() {
        return qtptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.QTPTime
     *
     * @param qtptime the value for Truck.QTPTime
     *
     * @mbg.generated
     */
    public void setQtptime(String qtptime) {
        this.qtptime = qtptime == null ? null : qtptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.QTNO
     *
     * @return the value of Truck.QTNO
     *
     * @mbg.generated
     */
    public String getQtno() {
        return qtno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.QTNO
     *
     * @param qtno the value for Truck.QTNO
     *
     * @mbg.generated
     */
    public void setQtno(String qtno) {
        this.qtno = qtno == null ? null : qtno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.GPSNO
     *
     * @return the value of Truck.GPSNO
     *
     * @mbg.generated
     */
    public String getGpsno() {
        return gpsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.GPSNO
     *
     * @param gpsno the value for Truck.GPSNO
     *
     * @mbg.generated
     */
    public void setGpsno(String gpsno) {
        this.gpsno = gpsno == null ? null : gpsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.MonitorCreate
     *
     * @return the value of Truck.MonitorCreate
     *
     * @mbg.generated
     */
    public Date getMonitorcreate() {
        return monitorcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.MonitorCreate
     *
     * @param monitorcreate the value for Truck.MonitorCreate
     *
     * @mbg.generated
     */
    public void setMonitorcreate(Date monitorcreate) {
        this.monitorcreate = monitorcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.attrbute1
     *
     * @return the value of Truck.attrbute1
     *
     * @mbg.generated
     */
    public String getAttrbute1() {
        return attrbute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.attrbute1
     *
     * @param attrbute1 the value for Truck.attrbute1
     *
     * @mbg.generated
     */
    public void setAttrbute1(String attrbute1) {
        this.attrbute1 = attrbute1 == null ? null : attrbute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.attrbute2
     *
     * @return the value of Truck.attrbute2
     *
     * @mbg.generated
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.attrbute2
     *
     * @param attrbute2 the value for Truck.attrbute2
     *
     * @mbg.generated
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2 == null ? null : attrbute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.attrbute3
     *
     * @return the value of Truck.attrbute3
     *
     * @mbg.generated
     */
    public String getAttrbute3() {
        return attrbute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.attrbute3
     *
     * @param attrbute3 the value for Truck.attrbute3
     *
     * @mbg.generated
     */
    public void setAttrbute3(String attrbute3) {
        this.attrbute3 = attrbute3 == null ? null : attrbute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.attrbute4
     *
     * @return the value of Truck.attrbute4
     *
     * @mbg.generated
     */
    public String getAttrbute4() {
        return attrbute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.attrbute4
     *
     * @param attrbute4 the value for Truck.attrbute4
     *
     * @mbg.generated
     */
    public void setAttrbute4(String attrbute4) {
        this.attrbute4 = attrbute4 == null ? null : attrbute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Truck.attrbute5
     *
     * @return the value of Truck.attrbute5
     *
     * @mbg.generated
     */
    public String getAttrbute5() {
        return attrbute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Truck.attrbute5
     *
     * @param attrbute5 the value for Truck.attrbute5
     *
     * @mbg.generated
     */
    public void setAttrbute5(String attrbute5) {
        this.attrbute5 = attrbute5 == null ? null : attrbute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", truckid=").append(truckid);
        sb.append(", licenseplate=").append(licenseplate);
        sb.append(", companyid=").append(companyid);
        sb.append(", companyname=").append(companyname);
        sb.append(", telephone=").append(telephone);
        sb.append(", address=").append(address);
        sb.append(", name=").append(name);
        sb.append(", weight=").append(weight);
        sb.append(", from=").append(from);
        sb.append(", qtpcreate=").append(qtpcreate);
        sb.append(", qtptime=").append(qtptime);
        sb.append(", qtno=").append(qtno);
        sb.append(", gpsno=").append(gpsno);
        sb.append(", monitorcreate=").append(monitorcreate);
        sb.append(", attrbute1=").append(attrbute1);
        sb.append(", attrbute2=").append(attrbute2);
        sb.append(", attrbute3=").append(attrbute3);
        sb.append(", attrbute4=").append(attrbute4);
        sb.append(", attrbute5=").append(attrbute5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}