package com.spring.service;

import java.util.List;

import com.spring.domain.Truck;
import com.spring.domain.UserInfo;
import com.spring.util.DataGrid;

public interface TruckService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    void delete(Truck[] truckid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    DataGrid<Truck> selectByPrimaryKey(Truck truck,int currentPage, int pageCount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    int update(Truck record);
}
