package com.spring.dao;

import com.spring.domain.Arearole;
import java.util.List;

public interface ArearoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaRole
     *
     * @mbg.generated
     */
    int insert(Arearole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaRole
     *
     * @mbg.generated
     */
    List<Arearole> selectAll();
}