package com.spring.dao;

import com.spring.domain.Areainfo;
import java.util.List;

public interface AreainfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areacode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaInfo
     *
     * @mbg.generated
     */
    int insert(Areainfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaInfo
     *
     * @mbg.generated
     */
    Areainfo selectByPrimaryKey(String areacode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaInfo
     *
     * @mbg.generated
     */
    List<Areainfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AreaInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Areainfo record);
}