package com.spring.dao;

import com.spring.domain.Companyinfo;
import java.math.BigDecimal;
import java.util.List;

public interface CompanyinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    int insert(Companyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    Companyinfo selectByPrimaryKey(BigDecimal companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    List<Companyinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CompanyInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Companyinfo record);
}