package com.spring.dao;

import com.spring.domain.Handmilksilos;
import java.math.BigDecimal;
import java.util.List;

public interface HandmilksilosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal hmsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    int insert(Handmilksilos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    Handmilksilos selectByPrimaryKey(BigDecimal hmsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    List<Handmilksilos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HandMilkSilos
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Handmilksilos record);
}