package com.spring.dao;

import com.spring.domain.Milkcontainerinfo;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MilkcontainerinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("mcid") BigDecimal mcid, @Param("companyid") BigDecimal companyid, @Param("mcno") String mcno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    int insert(Milkcontainerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    Milkcontainerinfo selectByPrimaryKey(@Param("mcid") BigDecimal mcid, @Param("companyid") BigDecimal companyid, @Param("mcno") String mcno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    List<Milkcontainerinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkContainerInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Milkcontainerinfo record);
}