package com.spring.dao;

import com.spring.domain.Milksequence;
import java.util.List;

public interface MilksequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkSequence
     *
     * @mbg.generated
     */
    int insert(Milksequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MilkSequence
     *
     * @mbg.generated
     */
    List<Milksequence> selectAll();
}