package com.spring.dao;

import com.spring.domain.SysPermission;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    List<SysPermission> selectAll();
    
    /**
     * 保存角色关联的资源信息
     * @param moduleIds 资源id集合
     * @param roleId 角色Id
     */
    @Insert({"<script>","insert ALL  <foreach item='item' index='index' collection='moduleIds'> INTO sys_permission (roleId, modelId) values  (#{roleId}, #{item}) </foreach> select 1 from dual","</script>"})
	int saveRoleModule(@Param("moduleIds")List<String> moduleIds, @Param("roleId")String roleId);
    /**
     * 删除角色下所有关联的资源信息
     * @param roleId
     */
    @Delete("delete from sys_permission where roleid = #{roleId}")
    void deleteRoleModule(@Param("roleId")String roleId);
    
    @Select("select roleId,modelId from sys_permission where roleid = #{roleId}")
    List<SysPermission> findSysPermissionByRoleId(@Param("roleId")String roleId);
}