package com.spring.dao;

import com.spring.domain.Truck;
import java.math.BigDecimal;
import java.util.List;

public interface TruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal truckid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    Truck selectByPrimaryKey(BigDecimal truckid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    List<Truck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Truck
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Truck record);
}