package com.spring.dao;

import com.spring.domain.Truckcompany;
import java.util.List;

public interface TruckcompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TruckCompany
     *
     * @mbg.generated
     */
    int insert(Truckcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TruckCompany
     *
     * @mbg.generated
     */
    List<Truckcompany> selectAll();
}